### ISSUE TITLE
Logout mechanism

### ISSUE THREAD

**Issue by Ghostriderdede** [gcorso97/fleamaster#16]
- Maybe a logout icon in the sidebar
- Cancel Session/ I don't know what needs to happen on the server site

**Comment by Ghostriderdede** [comment]
So - Will there be a request to the server? Like "cancelSessionToken"?
And back comes a value, which I can check in the frontend?

**Comment by gcorso97** [comment]
Yes, there will be a POST request, that handles the logout mechanism within the backend session and responds afterwards
