### ISSUE TITLE
After registration push back to the login

### ISSUE THREAD

**Issue by Ghostriderdede** [gcorso97/fleamaster#8]
The user should know that the registration was successful - Push to login so he can start. Maybe also an alert "Du hast dich erfolgreich registriert etc."

**Comment by Ghostriderdede** [comment]
Commit id: 7ff442da4798a2840b4c2f2dd466db50460327b3

**Comment by gcorso97** [comment]
Instead of navigation back, we should directly switch to welcome page after successful registration, because on the backend we already have a authenticated session @Ghostriderdede

**Comment by Ghostriderdede** [comment]
Fixed: commit b945a7a6d27545c282a8c1381f72702611563308
