### ISSUE TITLE
Buying and Selling Page are looking the same

### ISSUE THREAD

**Issue by Ghostriderdede** [gcorso97/fleamaster#9]
Some Issue with the isBuyer Property???

**Comment by gcorso97** [comment]
No, the isBuyer property is now dynamically set within URL query paramaters
e.g.
/products?isBuyer=true

**Comment by Ghostriderdede** [comment]
I added an event to the second card and switched the boolean parameter in the function:

@click="productsPage(false)

Before it wasn't even possible to navigate to the next page from the second page. Anyway - the page is still wrong

**Comment by gcorso97** [comment]
Fixed within be7ee1d1ebbdc3b5079eea2b3c368d61a4c19588
